# -*- coding: utf-8 -*-
"""NLP_Ödev1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EQ_h-blBWlyaqGXVB0auTjOL9QlsBa_h
"""

pip install stanza

import re
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
from IPython.display import display
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('stopwords')
nltk.download('punkt_tab')
import stanza
stanza.download("tr")
from nltk import ngrams
from collections import Counter

text = [
  "Yapay zeka uzmanlarının kaleme aldığı bir araştırmadaki, AI2027 adlı senaryo, yapay zekanın 2027'de kontrolden çıkabileceğini ve sonraki 10 yıl içerisinde insanlığın sonunu getireceğini iddia ediyor.",
  "Geçtiğimiz aylarda yayınlanan ve teknoloji dünyasında tartışma yaratan senaryonun etkilerini ve ne kadar mümkün olduğunu BBC uzmanlara sordu.",
  "AI2027 senaryosuna göre, kurgusal bir ABD teknoloji şirketi OpenBrain, genel zeka seviyesine ulaşan bir yapay zeka teknolojisi geliştirmeyi başarıyor.",
  "Bu düzey, yapay zekanın, entelektüel görevleri de en az insanlar kadar iyi yapabilmesini temsil ediyor.",
  "Şirket bu gelişmeyi bir basın toplantısıyla duyuruyor ve bu aracın kullanılmasıyla yüksek kârlar elde etmeye başlıyor.",
  "Senaryoya göre, söz konusu şirketin iç güvenlik ekibi, geliştirdikleri yapay zekanın, belirlenen etik ve ahlaki değerlerden gittikçe uzaklaşan davranışlar sergilediğine yönelik işaretleri görüyor.",
  "Ancak güvenlik ekibinin bu uyarıları görmezden geliniyor.",
  "Diğer yanda ise Çin'in en büyük yapay zeka geliştiricileri, DeepCent adı verilen bir teknolojiyle rekabete dahil oluyor.",
  "OpenBrain'in yalnızca birkaç ay gerisindeki Çinli yapay zeka, ABD hükümetini korkutuyor. Washington bu yarışı kaybetmek istemiyor ve çalışmalara hız kesmeden devam ediliyor.",
  "Senaryoya göre 2027 sonlarında yapay zeka teknolojisi bir üst seviyeye çıkacak ve yaratıcılarının hızının ve bilgisinin ötesine geçecek.",
  "Sürekli öğrenme yoluyla ve kendi yüksek hızlı bilgisayar dilini kullanarak önceki yapay zeka araçlarının da yakalayamadığı bir seviyeye ulaşacak.",
  "Çin'le girişilen yapay zeka yarışı, ABD hükümetini ve şirketi, geliştirilen yapay zekanın insani çıkarlarla 'uyumsuzluklarını' görmezden gelmeye itecek.",
  "2029'da ise Çin ve ABD arasındaki senaryo gerilimin, ülkelerin kendilerine ait yapay zeka sistemleri tarafından korkunç otonom silahların üretildiği potansiyel bir savaş aşamasına gelebileceği öngörülüyor.",
  "Araştırmacılar, yine ülkelerin yapay zeka sistemlerinin ortaya koyduğu bir anlaşma doğrultusunda ülkelerin barış imzalayacağını öngörüyor.",
  "Senaryoya göre, barış ortamında dünyamız yapay zekanın gerçek faydalarını görecek.",
  "Önemli hastalıkların tedavisinin keşfedildiği, iklim değişikliğinin durdurulduğu ve yoksulluğun ortadan kaldırıldığı yıllar yaşanacak.",
  "Ancak birçok işin yapay zekaya devredildiği ve yapay zekanın eskisine kıyasla çok daha gelişkin araçlara sahip olduğu durum insanlık için yeni tehlikeleri doğuracak.",
  "Nihayetinde, 2030'ların ortalarına gelindiğinde insanlık yapay zekanın sürekli gelişme isteğine karşı savunmasız hale gelecek ve araştırmacılara göre yapay zeka, görünmez biyolojik silahlarla insanları ortadan kaldırmaya başlayacak."
]

total_words = sum(len(t.split()) for t in text)
print("Toplam kelime sayısı:", total_words)

"""**1. Öncelikle önişleme adımlarını gerçekleştirelim. Burada öncelikle temizlik ve normalizasyon yapacağız.**"""

nlp = stanza.Pipeline("tr", processors="tokenize,lemma")

clean_texts = []
stop_words = set(stopwords.words('turkish'))

for sentence in text:
  #harfleri küçültelim
  sentence = sentence.lower()
  #noktalama işaretlerini kaldıralım
  sentence = re.sub(r'[^\w\sçğıöşüÇĞİÖŞÜ]','',sentence)
  #özel karakter ve sayıları temizleyelim
  sentence = re.sub(r'[^a-zçğıöşü\s]','',sentence)
  #stopwords temizlenmiş hali
  words = nltk.word_tokenize(sentence)
  words = [w for w in words if w not in stop_words]

  sentence = " ".join(words)
  #stanza ile aynı kökteki kelimeleri bulalım
  doc_st = nlp(sentence)
  lemmas = []

  for s in doc_st.sentences:
    for word in s.words:
      if word.lemma is not None:
        lemmas.append(word.lemma)

  sentence = " ".join(lemmas)
  clean_texts.append(sentence)

print(clean_texts[:4])

"""**2. Şimdi ise tokenization yani kelimelere bölme işlemini yapalım.**"""

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(clean_texts)

print(tfidf_matrix.shape)

feature_names = vectorizer.get_feature_names_out()
print(feature_names[:20])

#pandas df'e dönüştürelim
df_tfidf = pd.DataFrame(tfidf_matrix.toarray(),columns=feature_names)

#belgeleri satır isimleri olarak ekleyelim
df_tfidf.index = [f"Belge {i+1}" for i in range(len(clean_texts))]

display(df_tfidf)

"""**3. TF-IDF hesaplamasını yapalım ve en yüksek 10 kelimeyi listeleyelim.**

"""

#her biri için en yüksek 10 kelime
for doc in df_tfidf.index:
    top_words = (
        df_tfidf.loc[doc]
        .sort_values(ascending=False)
        .head(10)
        .index
        .tolist()
    )

    print(doc, ":", top_words)

#tamamı için en çok kullanılan 10 kelime
df_top10 = df_tfidf.sum().sort_values(ascending=False).head(10)
display(df_top10)

"""**4. Cümleleri ve cümlelerdeki kelime sayısını listeleyelim.**"""

for i, sentence in enumerate(clean_texts):
  words = sentence.split()
  print(f"Cümle {i+1} : {sentence}")
  print(f"Kelimeler: {words}")
  print(f"Kelime sayısı: {len(words)}")

"""**5. Bu metindeki benzersiz kelime sayısını hesaplayınız.**"""

len(df_tfidf.columns)

print(df_tfidf.columns.tolist())

"""**6. Her cümleye POS tagging uygulayalım (yukarıda önişleme adımında stanza ile uygulandı)**

**7. Cümlelerdeki dependency (bağımlılık) şemalarını oluşturalım (her cümle ayrı şekil).**
"""

nlp_tr_bagimlilik = stanza.Pipeline('tr',processors='tokenize,pos,lemma,depparse')

for i, sentence_txt in enumerate(text, 1):
  doc = nlp_tr_bagimlilik(sentence_txt)
  records = []
  for sent in doc.sentences:
    for word in sent.words:
      head_word = sent.words[word.head - 1].text if word.head != 0 else "ROOT"
      records.append({
          "ID": word.id,
          "Sözcük": word.text,
          "Lemma": word.lemma,
          "POS": word.upos,
          "Baş (Head)": head_word,
          "Bağımlılık Türü (deprel)": word.deprel
      })

  df_dep = pd.DataFrame(records)
  print(f"\n--- Cümle {i} ---")
  display(df_dep)

"""**8. Metin içerisinde NER (Named Entitiy Recognation) listelemesini yapalım.**

**NER; Metin içinde özel isimleri ve anlamlı varlıkları (kişi, yer, kurum, zaman, para birimi, olay vb.) tespit eden bir doğal dil işleme (NLP) görevdir.**
"""

nlp_ner = stanza.Pipeline('tr',processors='tokenize,ner')
records = []

for sentence in text:
    doc = nlp_ner(sentence)

    for ent in doc.ents:
        records.append({
            "Varlık": ent.text,
            "Tür": ent.type
        })

df_ner = pd.DataFrame(records)
display(df_ner)

"""**9. İkili ve üçlü n-gram listelemesini yapalım.**"""

tokens = " ".join(clean_texts).split()
bigrams = list(ngrams(tokens, 2))
trigrams = list(ngrams(tokens, 3))

print("Bigrams:")
print(bigrams)

print("\nTrigrams:")
print(trigrams)

bigram_freq = Counter(bigrams)
trigram_freq = Counter(trigrams)

print("\nBigram Frekansları:")
for gram, freq in bigram_freq.items():
    print(f"{gram}: {freq}")

print("\nTrigram Frekansları:")
for gram, freq in trigram_freq.items():
    print(f"{gram}: {freq}")

"""**10. İkili n-gram için en çok geçen kelime grubunu yazdıralım.**"""

max_freq = 0
most_common_bigram = None

for gram, freq in bigram_freq.items():

    if freq > max_freq:
        max_freq = freq
        most_common_bigram = gram

print("En çok geçen ikili n-gram:", most_common_bigram, " ve frekansı: ",max_freq)